const DATA = [
  {
    id: 0,
    name: "Adidas NMD",
    imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    price: 220,
    rating: 3,
    isAdded: false,
  },
  {
    id: 1,
    name: "Adidas Yeezy",
    imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
    price: 280,
    rating: 4,
    isAdded: false,
  },
  {
    id: 2,
    name: "Black Converse",
    imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
    price: 110,
    rating: 2,
    isAdded: false,
  },
  {
    id: 3,
    name: "Nike White AirForce",
    imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    price: 160,
    rating: 4,
    isAdded: false,
  },
  {
    id: 4,
    name: "Nike Red High Tops",
    imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
    price: 160,
    rating: 5,
    isAdded: false,
  },
  {
    id: 5,
    name: "Nike Brown High Tops",
    imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
    price: 160,
    rating: 2,
    isAdded: false,
  },
  {
    id: 6,
    name: "Air Jordan Limited",
    imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
    price: 190,
    rating: 4,
    isAdded: false,
  },
  {
    id: 7,
    name: "Timberlands",
    imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    price: 200,
    rating: 3,
    isAdded: false,
  },
];
export default DATA;
